stages:
  - validate
  - plan
  - apply

variables:
  AWS_DEFAULT_REGION: "ap-southeast-2"

.terraform_base: &terraform_base
  image:
    # Suggestion: instead of using the generic hashicorp/terraform:latest image (and installing extra tools via apk),
    # consider building and using a custom Terraform CI image (e.g. myorg/terraform-ci) with required dependencies preinstalled.
    # This ensures consistent versions, faster builds, and better reproducibility.
    name: hashicorp/terraform:latest 
    entrypoint: [""]
  id_tokens:
    GITLAB_OIDC_TOKEN:
      aud: https://gitlab.com
  variables:
    TF_HTTP_USERNAME: oauth2 # Don't change the default username
    TF_HTTP_PASSWORD: $GITLAB_ACCESS_TOKEN
  before_script:
    - apk add --no-cache aws-cli

# Non-Production Environment
.nonprod_base: &nonprod_base
  <<: *terraform_base
  variables:
    TF_ROOT: infrastructure/nonprod
  before_script:
    - apk add --no-cache aws-cli
    - >
      aws_sts_output=$(aws sts assume-role-with-web-identity
      --role-arn ${AWS_ROLE_ARN_NONPROD}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token ${GITLAB_OIDC_TOKEN}
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text)
    - export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" $aws_sts_output)
    - aws sts get-caller-identity
  only:
    - dev

# Production Environment (S3 Backend)
.prod_base: &prod_base
  <<: *terraform_base
  variables:
    TF_ROOT: infrastructure/prod
    TF_STATE_BUCKET: "chao-terraform-tf-state-bucket-780a"
    TF_STATE_KEY: "prod/terraform.tfstate"
    TF_STATE_REGION: "ap-southeast-2"
  before_script:
    - apk add --no-cache aws-cli
    - >
      aws_sts_output=$(aws sts assume-role-with-web-identity
      --role-arn ${AWS_ROLE_ARN_PROD}
      --role-session-name "GitLabRunner-${CI_PROJECT_ID}-${CI_PIPELINE_ID}"
      --web-identity-token ${GITLAB_OIDC_TOKEN}
      --duration-seconds 3600
      --query 'Credentials.[AccessKeyId,SecretAccessKey,SessionToken]'
      --output text)
    - export $(printf "AWS_ACCESS_KEY_ID=%s AWS_SECRET_ACCESS_KEY=%s AWS_SESSION_TOKEN=%s" $aws_sts_output)
    - aws sts get-caller-identity
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_COMMIT_TAG =~ /^prod-.*/

# Non-Production Jobs (validate/plan on all branches, apply only on dev)
validate_nonprod:
  <<: *nonprod_base
  stage: validate
  except:
    - main
  script:
    - cd $TF_ROOT
    - terraform init -backend-config="address=https://gitlab.com/api/v4/projects/75643650/terraform/state/chaodev-nonprod" -backend-config="lock_address=https://gitlab.com/api/v4/projects/75643650/terraform/state/chaodev-nonprod/lock" -backend-config="unlock_address=https://gitlab.com/api/v4/projects/75643650/terraform/state/chaodev-nonprod/lock" -backend-config="username=oauth2" -backend-config="password=$GITLAB_ACCESS_TOKEN"
    - terraform validate

plan_nonprod:
  <<: *nonprod_base
  stage: plan
  except:
    - main
  script:
    - cd $TF_ROOT
    - terraform init -backend-config="address=https://gitlab.com/api/v4/projects/75643650/terraform/state/chaodev-nonprod" -backend-config="lock_address=https://gitlab.com/api/v4/projects/75643650/terraform/state/chaodev-nonprod/lock" -backend-config="unlock_address=https://gitlab.com/api/v4/projects/75643650/terraform/state/chaodev-nonprod/lock" -backend-config="username=oauth2" -backend-config="password=$GITLAB_ACCESS_TOKEN"
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - infrastructure/nonprod/tfplan
    expire_in: 1 day

apply_nonprod:
  <<: *nonprod_base
  stage: apply
  only:
    - dev
  script:
    - cd $TF_ROOT
    - terraform init -backend-config="address=https://gitlab.com/api/v4/projects/75643650/terraform/state/chaodev-nonprod" -backend-config="lock_address=https://gitlab.com/api/v4/projects/75643650/terraform/state/chaodev-nonprod/lock" -backend-config="unlock_address=https://gitlab.com/api/v4/projects/75643650/terraform/state/chaodev-nonprod/lock" -backend-config="username=oauth2" -backend-config="password=$GITLAB_ACCESS_TOKEN"
    - terraform apply -auto-approve tfplan
  dependencies:
    - plan_nonprod

# Production Jobs (manual approval)
validate_prod:
  <<: *prod_base
  stage: validate
  script:
    - cd $TF_ROOT
    - terraform init -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="key=${TF_STATE_KEY}" -backend-config="region=${TF_STATE_REGION}"
    - terraform validate

plan_prod:
  <<: *prod_base
  stage: plan
  script:
    - cd $TF_ROOT
    - terraform init -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="key=${TF_STATE_KEY}" -backend-config="region=${TF_STATE_REGION}"
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - infrastructure/prod/tfplan
    expire_in: 1 week

apply_prod:
  <<: *prod_base
  stage: apply
  script:
    - cd $TF_ROOT
    - terraform init -backend-config="bucket=${TF_STATE_BUCKET}" -backend-config="key=${TF_STATE_KEY}" -backend-config="region=${TF_STATE_REGION}"
    - terraform apply -auto-approve tfplan
  dependencies:
    - plan_prod
  when: manual